apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-gbqfxllk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-gbqfxllk:azure-8f8514bef4d7359e099b2f7b0c1bf35b37a39833
          name: container-image
